name: 'ops-okta-query'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  okta-query:
    runs-on: ubuntu-latest
    steps:
      - name: 'find source IP'
        run: |
          curl ifconfig.me
