name: 'find-source-ip'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  find-source-ip:
    runs-on: ubuntu-latest
    steps:
      - name: 'find source IP'
        run: |
          curl ifconfig.me
