name: test-internal-repo

# Workflow triggered manually
on:
  workflow_dispatch: 
env:
  GH_TOKEN: ${{ github.token }}
    
jobs:
  stg-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout cspe-piam release by curl'
        run: |
           curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/octet-stream" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/cisco-sbg/cspe-piam/archive/refs/tags/test.tar.gz \
               -o test.tar.gz
           ls -al test.tar.gz
           echo "right after curl download" 
      - name: 'checkout cspe-piam release by gh cli'
        run: |
           gh release download -R "cisco-sbg/cspe-piam" test
           echo "right after gh download" 
